<?php

namespace Nettrine\Proxy\__CG__\App\Model\Database\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Photos extends \App\Model\Database\Entity\Photos implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'JP2FileSize' => [parent::class, 'JP2FileSize', null, 8],
        "\0".'*'."\0".'archiveFileSize' => [parent::class, 'archiveFileSize', null, 8],
        "\0".'*'."\0".'archiveFilename' => [parent::class, 'archiveFilename', null, 8],
        "\0".'*'."\0".'createdAt' => [parent::class, 'createdAt', null, 8],
        "\0".'*'."\0".'databotThumbFilename' => [parent::class, 'databotThumbFilename', null, 8],
        "\0".'*'."\0".'exif' => [parent::class, 'exif', null, 8],
        "\0".'*'."\0".'height' => [parent::class, 'height', null, 8],
        "\0".'*'."\0".'herbarium' => [parent::class, 'herbarium', null, 8],
        "\0".'*'."\0".'id' => [parent::class, 'id', null, 8],
        "\0".'*'."\0".'identify' => [parent::class, 'identify', null, 8],
        "\0".'*'."\0".'jp2Filename' => [parent::class, 'jp2Filename', null, 8],
        "\0".'*'."\0".'lastEdit' => [parent::class, 'lastEdit', null, 8],
        "\0".'*'."\0".'originalFileTimestamp' => [parent::class, 'originalFileTimestamp', null, 8],
        "\0".'*'."\0".'originalFilename' => [parent::class, 'originalFilename', null, 8],
        "\0".'*'."\0".'specimenId' => [parent::class, 'specimenId', null, 8],
        "\0".'*'."\0".'status' => [parent::class, 'status', null, 8],
        "\0".'*'."\0".'type' => [parent::class, 'type', null, 8],
        "\0".'*'."\0".'width' => [parent::class, 'width', null, 8],
        "\0".parent::class."\0".'databotResults' => [parent::class, 'databotResults', null, 16],
        "\0".parent::class."\0".'error' => [parent::class, 'error', null, 16],
        "\0".parent::class."\0".'multiplier' => [parent::class, 'multiplier', null, 16],
        'JP2FileSize' => [parent::class, 'JP2FileSize', null, 8],
        'archiveFileSize' => [parent::class, 'archiveFileSize', null, 8],
        'archiveFilename' => [parent::class, 'archiveFilename', null, 8],
        'createdAt' => [parent::class, 'createdAt', null, 8],
        'databotResults' => [parent::class, 'databotResults', null, 16],
        'databotThumbFilename' => [parent::class, 'databotThumbFilename', null, 8],
        'error' => [parent::class, 'error', null, 16],
        'exif' => [parent::class, 'exif', null, 8],
        'height' => [parent::class, 'height', null, 8],
        'herbarium' => [parent::class, 'herbarium', null, 8],
        'id' => [parent::class, 'id', null, 8],
        'identify' => [parent::class, 'identify', null, 8],
        'jp2Filename' => [parent::class, 'jp2Filename', null, 8],
        'lastEdit' => [parent::class, 'lastEdit', null, 8],
        'multiplier' => [parent::class, 'multiplier', null, 16],
        'originalFileTimestamp' => [parent::class, 'originalFileTimestamp', null, 8],
        'originalFilename' => [parent::class, 'originalFilename', null, 8],
        'specimenId' => [parent::class, 'specimenId', null, 8],
        'status' => [parent::class, 'status', null, 8],
        'type' => [parent::class, 'type', null, 8],
        'width' => [parent::class, 'width', null, 8],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
