<?php

namespace Nettrine\Proxy\__CG__\App\Model\Database\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ImageDownloadLog extends \App\Model\Database\Entity\ImageDownloadLog implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'createdAt' => [parent::class, 'createdAt', null, 8],
        "\0".'*'."\0".'id' => [parent::class, 'id', null, 8],
        "\0".'*'."\0".'imageType' => [parent::class, 'imageType', null, 8],
        "\0".'*'."\0".'ipAddress' => [parent::class, 'ipAddress', null, 8],
        "\0".'*'."\0".'photoId' => [parent::class, 'photoId', null, 8],
        "\0".'*'."\0".'referrer' => [parent::class, 'referrer', null, 8],
        "\0".'*'."\0".'userAgent' => [parent::class, 'userAgent', null, 8],
        'createdAt' => [parent::class, 'createdAt', null, 8],
        'id' => [parent::class, 'id', null, 8],
        'imageType' => [parent::class, 'imageType', null, 8],
        'ipAddress' => [parent::class, 'ipAddress', null, 8],
        'photoId' => [parent::class, 'photoId', null, 8],
        'referrer' => [parent::class, 'referrer', null, 8],
        'userAgent' => [parent::class, 'userAgent', null, 8],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
