<?php

namespace Nettrine\Proxy\__CG__\App\Model\Database\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CetafSid extends \App\Model\Database\Entity\CetafSid implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'collectionDate' => [parent::class, 'collectionDate', null, 8196],
        'collectorName' => [parent::class, 'collectorName', null, 8196],
        'collectorNumber' => [parent::class, 'collectorNumber', null, 8196],
        'createdAt' => [parent::class, 'createdAt', null, 8196],
        'family' => [parent::class, 'family', null, 8196],
        'herbarium' => [parent::class, 'herbarium', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'isoCountry' => [parent::class, 'isoCountry', null, 8196],
        'lastEdit' => [parent::class, 'lastEdit', null, 8196],
        'latitude' => [parent::class, 'latitude', null, 8196],
        'longitude' => [parent::class, 'longitude', null, 8196],
        'scientificNameCurrent' => [parent::class, 'scientificNameCurrent', null, 8196],
        'scientificNameOriginal' => [parent::class, 'scientificNameOriginal', null, 8196],
        'sourceLink' => [parent::class, 'sourceLink', null, 8196],
        'stableUri' => [parent::class, 'stableUri', null, 8196],
        'webscaledImageLink' => [parent::class, 'webscaledImageLink', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
