<?php

namespace Nettrine\Proxy\__CG__\App\Model\Database\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SpecimenMetadata extends \App\Model\Database\Entity\SpecimenMetadata implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'collection' => [parent::class, 'collection', null, 8196],
        'country' => [parent::class, 'country', null, 8196],
        'createdAt' => [parent::class, 'createdAt', null, 8196],
        'family' => [parent::class, 'family', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'lat' => [parent::class, 'lat', null, 8196],
        'lon' => [parent::class, 'lon', null, 8196],
        'photo' => [parent::class, 'photo', null, 8196],
        'pid' => [parent::class, 'pid', null, 8196],
        'taxon' => [parent::class, 'taxon', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
