<?php

namespace Nettrine\Proxy\__CG__\App\Model\Database\Entity\Views;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class VoucherVisionTranscription extends \App\Model\Database\Entity\Views\VoucherVisionTranscription implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'catalogNumber' => [parent::class, 'catalogNumber', null, 8196],
        'continent' => [parent::class, 'continent', null, 8196],
        'country' => [parent::class, 'country', null, 8196],
        'county' => [parent::class, 'county', null, 8196],
        'dateIdentified' => [parent::class, 'dateIdentified', null, 8196],
        'decimalLatitude' => [parent::class, 'decimalLatitude', null, 8196],
        'decimalLongitude' => [parent::class, 'decimalLongitude', null, 8196],
        'eventDate' => [parent::class, 'eventDate', null, 8196],
        'genus' => [parent::class, 'genus', null, 8196],
        'identifiedBy' => [parent::class, 'identifiedBy', null, 8196],
        'locality' => [parent::class, 'locality', null, 8196],
        'minimumElevationInMeters' => [parent::class, 'minimumElevationInMeters', null, 8196],
        'occurrenceRemarks' => [parent::class, 'occurrenceRemarks', null, 8196],
        'photo' => [parent::class, 'photo', null, 8196],
        'recordedBy' => [parent::class, 'recordedBy', null, 8196],
        'scientificName' => [parent::class, 'scientificName', null, 8196],
        'scientificNameAuthorship' => [parent::class, 'scientificNameAuthorship', null, 8196],
        'specificEpithet' => [parent::class, 'specificEpithet', null, 8196],
        'stateProvince' => [parent::class, 'stateProvince', null, 8196],
        'verbatimCoordinates' => [parent::class, 'verbatimCoordinates', null, 8196],
        'verbatimEventDate' => [parent::class, 'verbatimEventDate', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
