<?php

namespace Nettrine\Proxy\__CG__\App\Model\Database\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Model\Database\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'active' => [parent::class, 'active', null, 8],
        "\0".'*'."\0".'comment' => [parent::class, 'comment', null, 8],
        "\0".'*'."\0".'createdAt' => [parent::class, 'createdAt', null, 8],
        "\0".'*'."\0".'email' => [parent::class, 'email', null, 8],
        "\0".'*'."\0".'herbarium' => [parent::class, 'herbarium', null, 8],
        "\0".'*'."\0".'id' => [parent::class, 'id', null, 8],
        "\0".'*'."\0".'lastEdit' => [parent::class, 'lastEdit', null, 8],
        "\0".'*'."\0".'name' => [parent::class, 'name', null, 8],
        "\0".'*'."\0".'password' => [parent::class, 'password', null, 8],
        "\0".'*'."\0".'role' => [parent::class, 'role', null, 8],
        "\0".'*'."\0".'surname' => [parent::class, 'surname', null, 8],
        "\0".'*'."\0".'username' => [parent::class, 'username', null, 8],
        'active' => [parent::class, 'active', null, 8],
        'comment' => [parent::class, 'comment', null, 8],
        'createdAt' => [parent::class, 'createdAt', null, 8],
        'email' => [parent::class, 'email', null, 8],
        'herbarium' => [parent::class, 'herbarium', null, 8],
        'id' => [parent::class, 'id', null, 8],
        'lastEdit' => [parent::class, 'lastEdit', null, 8],
        'name' => [parent::class, 'name', null, 8],
        'password' => [parent::class, 'password', null, 8],
        'role' => [parent::class, 'role', null, 8],
        'surname' => [parent::class, 'surname', null, 8],
        'username' => [parent::class, 'username', null, 8],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
