<?php

namespace Nettrine\Proxy\__CG__\App\Model\Database\Entity\Views;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CetafHarvest extends \App\Model\Database\Entity\Views\CetafHarvest implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'associatedMedia' => [parent::class, 'associatedMedia', null, 8196],
        'basisOfRecord' => [parent::class, 'basisOfRecord', null, 8196],
        'catalogNumber' => [parent::class, 'catalogNumber', null, 8196],
        'collectionCode' => [parent::class, 'collectionCode', null, 8196],
        'country' => [parent::class, 'country', null, 8196],
        'countryCode' => [parent::class, 'countryCode', null, 8196],
        'created' => [parent::class, 'created', null, 8196],
        'creator' => [parent::class, 'creator', null, 8196],
        'description' => [parent::class, 'description', null, 8196],
        'eventDate' => [parent::class, 'eventDate', null, 8196],
        'family' => [parent::class, 'family', null, 8196],
        'fieldNumber' => [parent::class, 'fieldNumber', null, 8196],
        'genus' => [parent::class, 'genus', null, 8196],
        'lastEdit' => [parent::class, 'lastEdit', null, 8196],
        'locality' => [parent::class, 'locality', null, 8196],
        'materialSampleId' => [parent::class, 'materialSampleId', null, 8196],
        'photo' => [parent::class, 'photo', null, 8196],
        'previousIdentifications' => [parent::class, 'previousIdentifications', null, 8196],
        'publisher' => [parent::class, 'publisher', null, 8196],
        'recordNumber' => [parent::class, 'recordNumber', null, 8196],
        'recordedBy' => [parent::class, 'recordedBy', null, 8196],
        'scientificName' => [parent::class, 'scientificName', null, 8196],
        'specificEpithet' => [parent::class, 'specificEpithet', null, 8196],
        'thumbnail' => [parent::class, 'thumbnail', null, 8196],
        'title' => [parent::class, 'title', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
