<?php

namespace Nettrine\Proxy\__CG__\App\Model\Database\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CetafSid extends \App\Model\Database\Entity\CetafSid implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'barcode' => [parent::class, 'barcode', null, 8196],
        'countryCode' => [parent::class, 'countryCode', null, 8196],
        'createdAt' => [parent::class, 'createdAt', null, 8196],
        'dateIdentified' => [parent::class, 'dateIdentified', null, 8196],
        'decimalLatitude' => [parent::class, 'decimalLatitude', null, 8196],
        'decimalLongitude' => [parent::class, 'decimalLongitude', null, 8196],
        'eventDate' => [parent::class, 'eventDate', null, 8196],
        'externalIdFromInstitution' => [parent::class, 'externalIdFromInstitution', null, 8196],
        'family' => [parent::class, 'family', null, 8196],
        'fieldNumber' => [parent::class, 'fieldNumber', null, 8196],
        'herbarium' => [parent::class, 'herbarium', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'identifiedBy' => [parent::class, 'identifiedBy', null, 8196],
        'lastEdit' => [parent::class, 'lastEdit', null, 8196],
        'locality' => [parent::class, 'locality', null, 8196],
        'occurrenceRemarks' => [parent::class, 'occurrenceRemarks', null, 8196],
        'previousIdentifications' => [parent::class, 'previousIdentifications', null, 8196],
        'recordedBy' => [parent::class, 'recordedBy', null, 8196],
        'scientificName' => [parent::class, 'scientificName', null, 8196],
        'verbatimElevation' => [parent::class, 'verbatimElevation', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
