<?php

namespace Nettrine\Proxy\__CG__\App\Model\Database\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Databot extends \App\Model\Database\Entity\Databot implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'createdAt' => [parent::class, 'createdAt', null, 8],
        "\0".'*'."\0".'description' => [parent::class, 'description', null, 8],
        "\0".'*'."\0".'enabled' => [parent::class, 'enabled', null, 8],
        "\0".'*'."\0".'id' => [parent::class, 'id', null, 8],
        "\0".'*'."\0".'lastRun' => [parent::class, 'lastRun', null, 8],
        "\0".'*'."\0".'name' => [parent::class, 'name', null, 8],
        "\0".'*'."\0".'role' => [parent::class, 'role', null, 8],
        "\0".'*'."\0".'version' => [parent::class, 'version', null, 8],
        'createdAt' => [parent::class, 'createdAt', null, 8],
        'description' => [parent::class, 'description', null, 8],
        'enabled' => [parent::class, 'enabled', null, 8],
        'id' => [parent::class, 'id', null, 8],
        'lastRun' => [parent::class, 'lastRun', null, 8],
        'name' => [parent::class, 'name', null, 8],
        'role' => [parent::class, 'role', null, 8],
        'version' => [parent::class, 'version', null, 8],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
