<?php

namespace Nettrine\Proxy\__CG__\App\Model\Database\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Model\Database\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'active' => [parent::class, 'active', null, 8196],
        'comment' => [parent::class, 'comment', null, 8196],
        'createdAt' => [parent::class, 'createdAt', null, 8196],
        'email' => [parent::class, 'email', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'lastEdit' => [parent::class, 'lastEdit', null, 8196],
        'lastVisitedHerbarium' => [parent::class, 'lastVisitedHerbarium', null, 8196],
        'name' => [parent::class, 'name', null, 8196],
        'openidIdToken' => [parent::class, 'openidIdToken', null, 8196],
        'openidProvider' => [parent::class, 'openidProvider', null, 8196],
        'openidRefreshToken' => [parent::class, 'openidRefreshToken', null, 8196],
        'openidSubject' => [parent::class, 'openidSubject', null, 8196],
        'password' => [parent::class, 'password', null, 8196],
        'surname' => [parent::class, 'surname', null, 8196],
        'userHerbariumRoles' => [parent::class, 'userHerbariumRoles', null, 8196],
        'username' => [parent::class, 'username', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
