<?php

namespace Nettrine\Proxy\__CG__\App\Model\Database\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Herbaria extends \App\Model\Database\Entity\Herbaria implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'acronym' => [parent::class, 'acronym', null, 8196],
        'address' => [parent::class, 'address', null, 8196],
        'bucket' => [parent::class, 'bucket', null, 8196],
        'contacts' => [parent::class, 'contacts', null, 8196],
        'externalDatabase' => [parent::class, 'externalDatabase', null, 8196],
        'fallbackFilename' => [parent::class, 'fallbackFilename', null, 8196],
        'fullname' => [parent::class, 'fullname', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'license' => [parent::class, 'license', null, 8196],
        'logo' => [parent::class, 'logo', null, 8196],
        'multipleBarcodeMultiplier' => [parent::class, 'multipleBarcodeMultiplier', null, 8196],
        'photos' => [parent::class, 'photos', null, 8196],
        'regexBarcode' => [parent::class, 'regexBarcode', null, 8196],
        'regexFilename' => [parent::class, 'regexFilename', null, 8196],
        'userHerbariumRoles' => [parent::class, 'userHerbariumRoles', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
