<?php

namespace Nettrine\Proxy\__CG__\App\Model\Database\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ImportError extends \App\Model\Database\Entity\ImportError implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'barcodes' => [parent::class, 'barcodes', null, 8],
        "\0".'*'."\0".'duplicateTo' => [parent::class, 'duplicateTo', null, 8],
        "\0".'*'."\0".'id' => [parent::class, 'id', null, 8],
        "\0".'*'."\0".'message' => [parent::class, 'message', null, 8],
        "\0".'*'."\0".'photo' => [parent::class, 'photo', null, 8],
        "\0".'*'."\0".'thumbnail' => [parent::class, 'thumbnail', null, 8],
        'barcodes' => [parent::class, 'barcodes', null, 8],
        'duplicateTo' => [parent::class, 'duplicateTo', null, 8],
        'id' => [parent::class, 'id', null, 8],
        'message' => [parent::class, 'message', null, 8],
        'photo' => [parent::class, 'photo', null, 8],
        'thumbnail' => [parent::class, 'thumbnail', null, 8],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
