<?php

namespace Nettrine\Proxy\__CG__\App\Model\Database\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DatabotResult extends \App\Model\Database\Entity\DatabotResult implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'createdAt' => [parent::class, 'createdAt', null, 8],
        "\0".'*'."\0".'databot' => [parent::class, 'databot', null, 8],
        "\0".'*'."\0".'id' => [parent::class, 'id', null, 8],
        "\0".'*'."\0".'message' => [parent::class, 'message', null, 8],
        "\0".'*'."\0".'photo' => [parent::class, 'photo', null, 8],
        "\0".'*'."\0".'resultData' => [parent::class, 'resultData', null, 8],
        "\0".'*'."\0".'status' => [parent::class, 'status', null, 8],
        'createdAt' => [parent::class, 'createdAt', null, 8],
        'databot' => [parent::class, 'databot', null, 8],
        'id' => [parent::class, 'id', null, 8],
        'message' => [parent::class, 'message', null, 8],
        'photo' => [parent::class, 'photo', null, 8],
        'resultData' => [parent::class, 'resultData', null, 8],
        'status' => [parent::class, 'status', null, 8],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
