<?php

namespace Nettrine\Proxy\__CG__\App\Model\Database\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Photos extends \App\Model\Database\Entity\Photos implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        'JP2FileSize' => [parent::class, 'JP2FileSize', null, 8196],
        'archiveFileChecksum' => [parent::class, 'archiveFileChecksum', null, 8196],
        'archiveFileSize' => [parent::class, 'archiveFileSize', null, 8196],
        'archiveFilename' => [parent::class, 'archiveFilename', null, 8196],
        'bucketSuffix' => [parent::class, 'bucketSuffix', null, 8196],
        'createdAt' => [parent::class, 'createdAt', null, 8196],
        'databotResults' => [parent::class, 'databotResults', null, 8196],
        'databotThumbFilename' => [parent::class, 'databotThumbFilename', null, 8196],
        'embargoTimeout' => [parent::class, 'embargoTimeout', null, 8196],
        'error' => [parent::class, 'error', null, 8196],
        'exif' => [parent::class, 'exif', null, 8196],
        'funding' => [parent::class, 'funding', null, 8196],
        'height' => [parent::class, 'height', null, 8196],
        'herbarium' => [parent::class, 'herbarium', null, 8196],
        'id' => [parent::class, 'id', null, 8196],
        'identify' => [parent::class, 'identify', null, 8196],
        'jp2Filename' => [parent::class, 'jp2Filename', null, 8196],
        'lastEdit' => [parent::class, 'lastEdit', null, 8196],
        'multiplier' => [parent::class, 'multiplier', null, 8196],
        'originalFileTimestamp' => [parent::class, 'originalFileTimestamp', null, 8196],
        'originalFilename' => [parent::class, 'originalFilename', null, 8196],
        'pid' => [parent::class, 'pid', null, 8196],
        'specimenId' => [parent::class, 'specimenId', null, 8196],
        'specimenMetadata' => [parent::class, 'specimenMetadata', null, 8196],
        'specimenPid' => [parent::class, 'specimenPid', null, 8196],
        'status' => [parent::class, 'status', null, 8196],
        'type' => [parent::class, 'type', null, 8196],
        'width' => [parent::class, 'width', null, 8196],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
