<?php

declare(strict_types=1);

namespace Database\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250724114035 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'introduce databot registry';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TYPE enum_databot_role AS ENUM (\'validator\', \'scanner\', \'exporter\');');
        $this->addSql('CREATE TYPE enum_databot_result_status AS ENUM (\'ok\', \'error\', \'warning\', \'skipped\');');

        $this->addSql('CREATE TABLE databot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, name VARCHAR(255) NOT NULL, description text NOT NULL, role enum_databot_role NOT NULL DEFAULT \'validator\', version INT NOT NULL, enabled BOOLEAN DEFAULT true NOT NULL, last_run TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,  PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_50AB601D5E237E06 ON databot (name, version)');
        $this->addSql('COMMENT ON TABLE databot IS \'List of bots registered\'');
        $this->addSql('COMMENT ON COLUMN databot.name IS \'Short name of Databot\'');
        $this->addSql('CREATE TABLE databot_results (status enum_databot_result_status NOT NULL DEFAULT \'ok\', message TEXT DEFAULT NULL, result_data JSONB DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, databot_id INT NOT NULL, photo_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CC2B43905646E484 ON databot_results (databot_id)');
        $this->addSql('CREATE INDEX IDX_CC2B43907E9E4C8C ON databot_results (photo_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CC2B43905646E4847E9E4C8C ON databot_results (databot_id, photo_id)');
        $this->addSql('COMMENT ON TABLE databot_results IS \'Results of Databot runs per photo\'');
        $this->addSql('COMMENT ON COLUMN databot_results.status IS \'Result status: ok, error, warning...\'');
        $this->addSql('COMMENT ON COLUMN databot_results.message IS \'Optional log or error description\'');
        $this->addSql('COMMENT ON COLUMN databot_results.result_data IS \'Structured result data, e.g. metrics, checks\'');
        $this->addSql('ALTER TABLE databot_results ADD CONSTRAINT FK_CC2B43905646E484 FOREIGN KEY (databot_id) REFERENCES databot (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE databot_results ADD CONSTRAINT FK_CC2B43907E9E4C8C FOREIGN KEY (photo_id) REFERENCES photos (id) ON DELETE CASCADE NOT DEFERRABLE');
        //sample call is SELECT register_databot('plagiary_bot', 'Detects duplicates', 3, 'scanner');
        //-- => true nebo false
        $this->addSql('
        CREATE OR REPLACE FUNCTION register_databot(
    p_name TEXT,
    p_description TEXT,
    p_version INTEGER,
    p_role enum_databot_role
)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $$
DECLARE
    existing_bot_id INT;
    existing_enabled BOOLEAN;
BEGIN
    -- Najdi bota podle jména a verze
    SELECT id, enabled
    INTO existing_bot_id, existing_enabled
    FROM databot
    WHERE name = p_name AND version = p_version;

    IF FOUND THEN
        IF existing_enabled THEN
            -- Verze existuje a je povolená – aktualizuj last_run
            UPDATE databot
            SET last_run = NOW(),
            description = p_description
            WHERE id = existing_bot_id;

            RETURN TRUE;
        ELSE
            -- Verze existuje, ale je zakázaná – neumožni spuštění
            RETURN FALSE;
        END IF;
    ELSE
        -- Zakázat všechny starší verze se stejným jménem
        UPDATE databot
        SET enabled = FALSE
        WHERE name = p_name AND version < p_version;

        -- Vložit nového bota
        INSERT INTO databot (
            name, description, version, role, enabled,
            created_at, last_run
        )
        VALUES (
            p_name, p_description, p_version, p_role, TRUE,
            NOW(), NOW()
        );

        RETURN TRUE;
    END IF;
END;
$$;
');
        $this->addSql('COMMENT ON FUNCTION register_databot(TEXT, TEXT, INTEGER, enum_databot_role)
IS \'Register databot. Return TRUE if a databot is successfully registered and allowed to proceed, otherwise returns FALSE - that mean dependabot should stop and leave.\';');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE databot_results DROP CONSTRAINT FK_CC2B43905646E484');
        $this->addSql('ALTER TABLE databot_results DROP CONSTRAINT FK_CC2B43907E9E4C8C');
        $this->addSql('DROP TABLE databot');
        $this->addSql('DROP TABLE databot_results');
        $this->addSql('DROP TYPE enum_databot_role');
        $this->addSql('DROP TYPE enum_databot_result_status');
        $this->addSql('DROP FUNCTION register_databot');
    }
}
