<?php

declare(strict_types=1);

namespace Database\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250725081640 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'maintenace table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE front.maintenance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,message VARCHAR(255) NOT NULL, type VARCHAR(255) DEFAULT \'info\' NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,  PRIMARY KEY (id))');
        $this->addSql('COMMENT ON TABLE front.maintenance IS \'Manually edited table with maintenance information.\'');
        $this->addSql('COMMENT ON COLUMN front.maintenance.type IS \'success | info | warning | danger = Bootstrap contextual classes\'');
        $this->addSql('COMMENT ON COLUMN front.maintenance.expires_at IS \'The message will be hidden when expired\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE front.maintenance');
    }
}
