<?php

declare(strict_types=1);

namespace Database\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20250725064059 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'use new Postgres identity id column provider';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE front.contact ALTER id TYPE INT');
        $this->addSql('ALTER TABLE front.contact ALTER id DROP DEFAULT');
        $this->addSql('DROP SEQUENCE IF EXISTS front.contact_id_seq;');
        $this->addSql('ALTER TABLE front.contact ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('SELECT setval(pg_get_serial_sequence(\'front.contact\', \'id\'), (SELECT MAX(id) + 1 FROM front.contact));');

        $this->addSql('ALTER TABLE herbaria ALTER id TYPE INT');
        $this->addSql('ALTER TABLE herbaria ALTER id DROP DEFAULT');
        $this->addSql('DROP SEQUENCE IF EXISTS herbaria_id_seq;');
        $this->addSql('ALTER TABLE herbaria ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('SELECT setval(pg_get_serial_sequence(\'herbaria\', \'id\'), (SELECT MAX(id) + 1 FROM herbaria));');

        $this->addSql('ALTER TABLE photos ALTER id TYPE INT');
        $this->addSql('ALTER TABLE photos ALTER id DROP DEFAULT');
        $this->addSql('DROP SEQUENCE IF EXISTS photos_id_seq;');
        $this->addSql('ALTER TABLE photos ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('SELECT setval(pg_get_serial_sequence(\'photos\', \'id\'), (SELECT MAX(id) + 1 FROM photos));');

        $this->addSql('ALTER TABLE import_error ALTER id TYPE INT');
        $this->addSql('ALTER TABLE import_error ALTER id DROP DEFAULT');
        $this->addSql('DROP SEQUENCE IF EXISTS import_error_id_seq;');
        $this->addSql('ALTER TABLE import_error ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('SELECT setval(pg_get_serial_sequence(\'import_error\', \'id\'), (SELECT MAX(id) + 1 FROM import_error));');

        $this->addSql('ALTER TABLE photos_status ALTER id TYPE INT');
        $this->addSql('ALTER TABLE photos_status ALTER id DROP DEFAULT');
        $this->addSql('DROP SEQUENCE IF EXISTS photos_status_id_seq;');
        $this->addSql('ALTER TABLE photos_status ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('SELECT setval(pg_get_serial_sequence(\'photos_status\', \'id\'), (SELECT MAX(id) + 1 FROM photos_status));');

        $this->addSql('ALTER TABLE photos_type ALTER id TYPE INT');
        $this->addSql('ALTER TABLE photos_type ALTER id DROP DEFAULT');
        $this->addSql('DROP SEQUENCE IF EXISTS photos_type_id_seq;');
        $this->addSql('ALTER TABLE photos_type ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('SELECT setval(pg_get_serial_sequence(\'photos_type\', \'id\'), (SELECT MAX(id) + 1 FROM photos_type));');

        $this->addSql('ALTER TABLE users ALTER id TYPE INT');
        $this->addSql('ALTER TABLE users ALTER id DROP DEFAULT');
        $this->addSql('DROP SEQUENCE IF EXISTS users_id_seq;');
        $this->addSql('ALTER TABLE users ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('SELECT setval(pg_get_serial_sequence(\'users\', \'id\'), (SELECT MAX(id) + 1 FROM users));');

        $this->addSql('ALTER TABLE usersrole ALTER id TYPE INT');
        $this->addSql('ALTER TABLE usersrole ALTER id DROP DEFAULT');
        $this->addSql('DROP SEQUENCE IF EXISTS usersrole_id_seq;');
        $this->addSql('ALTER TABLE usersrole ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('SELECT setval(pg_get_serial_sequence(\'usersrole\', \'id\'), (SELECT MAX(id) + 1 FROM usersrole));');
    }

    public function down(Schema $schema): void
    {


    }
}
