<?php

declare(strict_types=1);

namespace Database\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260902093334 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('DROP TABLE cache.specimen_metadata');
        $this->addSql('DROP SCHEMA cache');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE SCHEMA cache');
        $this->addSql('CREATE TABLE cache.specimen_metadata (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, photo_id INT DEFAULT NULL, pid VARCHAR(255) DEFAULT NULL, family VARCHAR(255) DEFAULT NULL, taxon VARCHAR(255) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, lat DOUBLE PRECISION DEFAULT NULL, lon DOUBLE PRECISION DEFAULT NULL, collection VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_d2b00d087e9e4c8c ON cache.specimen_metadata (photo_id)');
        $this->addSql('ALTER TABLE cache.specimen_metadata ADD CONSTRAINT fk_d2b00d087e9e4c8c FOREIGN KEY (photo_id) REFERENCES photos (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
