<?php

declare(strict_types=1);

namespace Database\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251006115320 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE external_database (name VARCHAR(255) NOT NULL, url VARCHAR(255) NOT NULL, element varchar(255), description TEXT DEFAULT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E34A3ED65E237E06 ON external_database (name)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E34A3ED6F47645AE ON external_database (url)');
        $this->addSql('ALTER TABLE herbaria ADD external_database_id INT NOT NULL DEFAULT 1');
        $this->addSql('ALTER TABLE herbaria ADD CONSTRAINT FK_40DF22BA986D44AC FOREIGN KEY (external_database_id) REFERENCES external_database (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_40DF22BA986D44AC ON herbaria (external_database_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE external_database');
        $this->addSql('ALTER TABLE herbaria DROP CONSTRAINT FK_40DF22BA986D44AC');
        $this->addSql('DROP INDEX IDX_40DF22BA986D44AC');
        $this->addSql('ALTER TABLE herbaria DROP external_database_id');
    }
}
