<?php

declare(strict_types=1);

namespace Database\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251016102136 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE public.funding (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, lastedit_timestamp TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(255) DEFAULT NULL, funder VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, note TEXT DEFAULT NULL, ccmm_format TEXT DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL,  herbarium_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E8291F6ADD127992 ON public.funding (herbarium_id)');
        $this->addSql('ALTER TABLE public.funding ADD CONSTRAINT FK_E8291F6ADD127992 FOREIGN KEY (herbarium_id) REFERENCES herbaria (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE photos ADD funding_id INT DEFAULT NULL');
        $this->addSql('COMMENT ON COLUMN photos.funding_id IS \'Funding\'');
        $this->addSql('ALTER TABLE photos ADD CONSTRAINT FK_876E0D99D70482 FOREIGN KEY (funding_id) REFERENCES public.funding (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_876E0D99D70482 ON photos (funding_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE photos DROP CONSTRAINT FK_876E0D99D70482');
        $this->addSql('DROP INDEX IDX_876E0D99D70482');
        $this->addSql('ALTER TABLE photos DROP funding_id');
        $this->addSql('ALTER TABLE public.funding DROP CONSTRAINT FK_E8291F6ADD127992');
        $this->addSql('DROP TABLE public.funding');
    }
}
