<?php

declare(strict_types=1);

namespace Database\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250925070824 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE image_download_requests (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, photo_id INT NOT NULL, image_type VARCHAR(255) NOT NULL, ip_address VARCHAR(255) DEFAULT NULL, user_agent VARCHAR(255) DEFAULT NULL, is_front_ui BOOLEAN DEFAULT false NOT NULL, referrer VARCHAR(255) DEFAULT NULL,  created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id))');
        $this->addSql('COMMENT ON TABLE image_download_requests IS \'Image download requests\'');
        $this->addSql('COMMENT ON COLUMN image_download_requests.photo_id IS \'ID of the photo being downloaded\'');
        $this->addSql('COMMENT ON COLUMN image_download_requests.image_type IS \'Type of image being downloaded (archive, jp2, databot_thumb)\'');
        $this->addSql('COMMENT ON COLUMN image_download_requests.ip_address IS \'IP address of the requester\'');
        $this->addSql('COMMENT ON COLUMN image_download_requests.user_agent IS \'User agent of the requester\'');
        $this->addSql('COMMENT ON COLUMN image_download_requests.is_front_ui IS \'Whether the download was from Admin UI (false) or Front UI (true)\'');
        $this->addSql('COMMENT ON COLUMN image_download_requests.referrer IS \'Referrer URL\'');
        $this->addSql('CREATE TABLE user_herbarium_role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, herbarium_id INT NOT NULL, role_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3F2FBFB7A76ED395 ON user_herbarium_role (user_id)');
        $this->addSql('CREATE INDEX IDX_3F2FBFB7DD127992 ON user_herbarium_role (herbarium_id)');
        $this->addSql('CREATE INDEX IDX_3F2FBFB7D60322AC ON user_herbarium_role (role_id)');
        $this->addSql('COMMENT ON TABLE user_herbarium_role IS \'User roles in specific herbaria\'');
        $this->addSql('ALTER TABLE user_herbarium_role ADD CONSTRAINT FK_3F2FBFB7A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_herbarium_role ADD CONSTRAINT FK_3F2FBFB7DD127992 FOREIGN KEY (herbarium_id) REFERENCES herbaria (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_herbarium_role ADD CONSTRAINT FK_3F2FBFB7D60322AC FOREIGN KEY (role_id) REFERENCES usersrole (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_herbaria DROP CONSTRAINT fk_a052c6baa76ed395');
        $this->addSql('ALTER TABLE user_herbaria DROP CONSTRAINT fk_a052c6ba1f5637d3');
        $this->addSql('INSERT INTO user_herbarium_role (user_id, herbarium_id, role_id) SELECT user_id, herbaria_id, 3 FROM user_herbaria');
        $this->addSql('DROP TABLE user_herbaria');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT fk_1483a5e9d60322ac');
        $this->addSql('DROP INDEX idx_1483a5e9d60322ac');
        $this->addSql('ALTER TABLE users DROP role_id');

        $this->addSql('CREATE TABLE front.image_download_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, photo_id INT NOT NULL, image_type VARCHAR(255) NOT NULL, ip_address VARCHAR(255) DEFAULT NULL, user_agent VARCHAR(255) DEFAULT NULL, referrer VARCHAR(255) DEFAULT NULL,  PRIMARY KEY (id))');
        $this->addSql('COMMENT ON TABLE front.image_download_log IS \'Image download log\'');
        $this->addSql('COMMENT ON COLUMN front.image_download_log.photo_id IS \'ID of the photo being downloaded\'');
        $this->addSql('COMMENT ON COLUMN front.image_download_log.image_type IS \'Type of image being downloaded (archive, jp2, databot_thumb)\'');
        $this->addSql('COMMENT ON COLUMN front.image_download_log.ip_address IS \'IP address of the requester\'');
        $this->addSql('COMMENT ON COLUMN front.image_download_log.user_agent IS \'User agent of the requester\'');
        $this->addSql('COMMENT ON COLUMN front.image_download_log.referrer IS \'Referrer URL\'');
        $this->addSql('DROP TABLE image_download_requests');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE image_download_requests (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, photo_id INT NOT NULL, image_type VARCHAR(255) NOT NULL, ip_address VARCHAR(255) DEFAULT NULL, user_agent VARCHAR(255) DEFAULT NULL, is_front_ui BOOLEAN DEFAULT false NOT NULL, referrer VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id))');
        $this->addSql('COMMENT ON TABLE image_download_requests IS \'Image download requests\'');
        $this->addSql('COMMENT ON COLUMN image_download_requests.photo_id IS \'ID of the photo being downloaded\'');
        $this->addSql('COMMENT ON COLUMN image_download_requests.image_type IS \'Type of image being downloaded (archive, jp2, databot_thumb)\'');
        $this->addSql('COMMENT ON COLUMN image_download_requests.ip_address IS \'IP address of the requester\'');
        $this->addSql('COMMENT ON COLUMN image_download_requests.user_agent IS \'User agent of the requester\'');
        $this->addSql('COMMENT ON COLUMN image_download_requests.is_front_ui IS \'Whether the download was from Admin UI (false) or Front UI (true)\'');
        $this->addSql('COMMENT ON COLUMN image_download_requests.referrer IS \'Referrer URL\'');
        $this->addSql('DROP TABLE front.image_download_log');


        $this->addSql('CREATE TABLE user_herbaria (user_id INT NOT NULL, herbaria_id INT NOT NULL, PRIMARY KEY (user_id, herbaria_id))');
        $this->addSql('CREATE INDEX idx_a052c6ba1f5637d3 ON user_herbaria (herbaria_id)');
        $this->addSql('CREATE INDEX idx_a052c6baa76ed395 ON user_herbaria (user_id)');
        $this->addSql('ALTER TABLE user_herbaria ADD CONSTRAINT fk_a052c6baa76ed395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_herbaria ADD CONSTRAINT fk_a052c6ba1f5637d3 FOREIGN KEY (herbaria_id) REFERENCES herbaria (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_herbarium_role DROP CONSTRAINT FK_3F2FBFB7A76ED395');
        $this->addSql('ALTER TABLE user_herbarium_role DROP CONSTRAINT FK_3F2FBFB7DD127992');
        $this->addSql('ALTER TABLE user_herbarium_role DROP CONSTRAINT FK_3F2FBFB7D60322AC');
        $this->addSql('DROP TABLE image_download_requests');
        $this->addSql('DROP TABLE user_herbarium_role');
        $this->addSql('ALTER TABLE users ADD role_id INT NOT NULL');
        $this->addSql('COMMENT ON COLUMN users.role_id IS \'Role for ACL\'');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT fk_1483a5e9d60322ac FOREIGN KEY (role_id) REFERENCES usersrole (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_1483a5e9d60322ac ON users (role_id)');
    }
}
