<?php

declare(strict_types=1);

namespace Database\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251006124303 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA cache');
        $this->addSql('CREATE TABLE cache.specimen_metadata (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,  created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, photo_id INT DEFAULT NULL, pid VARCHAR(255) DEFAULT NULL, family VARCHAR(255) DEFAULT NULL, taxon VARCHAR(255) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, lat DOUBLE PRECISION DEFAULT NULL, lon DOUBLE PRECISION DEFAULT NULL, collection VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D2B00D087E9E4C8C ON cache.specimen_metadata (photo_id)');
        $this->addSql('ALTER TABLE cache.specimen_metadata ADD CONSTRAINT FK_D2B00D087E9E4C8C FOREIGN KEY (photo_id) REFERENCES photos (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE external_database ALTER element SET NOT NULL');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_265FB4DD41405E39 ON external_database (element)');
        $this->addSql('ALTER INDEX uniq_e34a3ed65e237e06 RENAME TO UNIQ_265FB4DD5E237E06');
        $this->addSql('ALTER INDEX uniq_e34a3ed6f47645ae RENAME TO UNIQ_265FB4DDF47645AE');
        $this->addSql('ALTER TABLE herbaria ALTER external_database_id DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cache.specimen_metadata DROP CONSTRAINT FK_D2B00D087E9E4C8C');
        $this->addSql('DROP TABLE cache.specimen_metadata');
        $this->addSql('DROP INDEX UNIQ_265FB4DD41405E39');
        $this->addSql('ALTER TABLE external_database ALTER element DROP NOT NULL');
        $this->addSql('ALTER INDEX uniq_265fb4ddf47645ae RENAME TO uniq_e34a3ed6f47645ae');
        $this->addSql('ALTER INDEX uniq_265fb4dd5e237e06 RENAME TO uniq_e34a3ed65e237e06');
        $this->addSql('ALTER TABLE herbaria ALTER external_database_id SET DEFAULT 1');
    }
}
