<?php

declare(strict_types=1);

namespace Database\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251014111249 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE front.excluded_download_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ip VARCHAR(255) NOT NULL, description VARCHAR(255) NOT NULL,  PRIMARY KEY (id))');
        $this->addSql('COMMENT ON TABLE front.excluded_download_log IS \'IP addresses excluded from download logging\'');
        $this->addSql('COMMENT ON COLUMN front.excluded_download_log.ip IS \'IP address to be excluded from logging\'');
        $this->addSql('COMMENT ON COLUMN front.excluded_download_log.description IS \'Description of why this IP is excluded\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE front.excluded_download_log');
    }
}
