<?php

declare(strict_types=1);

namespace Database\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250830105650 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE import_multiplier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, barcodes JSON NOT NULL,  photo_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_661097487E9E4C8C ON import_multiplier (photo_id)');
        $this->addSql('COMMENT ON TABLE import_multiplier IS \'Holds remaining valid IDs of mixed specimens (with multiple barcodes) to be cloned during the import process\'');
        $this->addSql('COMMENT ON COLUMN import_multiplier.photo_id IS \'photo to which this multiplier belongs\'');
        $this->addSql('ALTER TABLE import_multiplier ADD CONSTRAINT FK_661097487E9E4C8C FOREIGN KEY (photo_id) REFERENCES photos (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER INDEX uniq_8a47742d7e9e4c8c RENAME TO UNIQ_B08813BF7E9E4C8C');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE import_multiplier DROP CONSTRAINT FK_661097487E9E4C8C');
        $this->addSql('DROP TABLE import_multiplier');
        $this->addSql('ALTER INDEX uniq_b08813bf7e9e4c8c RENAME TO uniq_8a47742d7e9e4c8c');
    }
}
