<?php

declare(strict_types=1);

namespace Database\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250829100649 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE license (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, acronym VARCHAR(255) NOT NULL, link text NOT NULL, is_default bool NOT NULL default FALSE,  PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5768F419512D8851 ON license (acronym)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5768F41936AC99F1 ON license (link)');
        $this->addSql('COMMENT ON TABLE license IS \'Licenses available in the repository\'');
        $this->addSql('COMMENT ON COLUMN license.acronym IS \'acronym\'');
        $this->addSql('COMMENT ON COLUMN license.link IS \'link to full text\'');
        $this->addSql('ALTER TABLE herbaria ADD license_id INT NOT NULL default 1');
        $this->addSql('ALTER TABLE herbaria ALTER COLUMN license_id DROP default');
        $this->addSql('ALTER TABLE herbaria ADD CONSTRAINT FK_40DF22BA460F904B FOREIGN KEY (license_id) REFERENCES license (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_40DF22BA460F904B ON herbaria (license_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE herbaria DROP CONSTRAINT FK_40DF22BA460F904B');
        $this->addSql('DROP INDEX IDX_40DF22BA460F904B');
        $this->addSql('ALTER TABLE herbaria DROP license_id');
        $this->addSql('DROP TABLE license');
    }
}
