<?php

declare(strict_types=1);

namespace Database\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251218091830 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'cetaf SID table';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA cetaf');
        $this->addSql('CREATE TABLE cetaf.sid (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, lastedit_timestamp TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, herbarium INT NOT NULL, external_id_from_institution VARCHAR(255) NOT NULL, barcode VARCHAR(255) NOT NULL, stable_uri VARCHAR(255) DEFAULT NULL, scientific_name VARCHAR(255) DEFAULT NULL, identified_by VARCHAR(255) DEFAULT NULL, date_identified VARCHAR(255) DEFAULT NULL, family VARCHAR(255) DEFAULT NULL, verbatim_identification VARCHAR(255) DEFAULT NULL, field_number VARCHAR(255) DEFAULT NULL, locality VARCHAR(255) DEFAULT NULL, verbatim_elevation VARCHAR(255) DEFAULT NULL, occurrence_remarks VARCHAR(255) DEFAULT NULL, recorded_by VARCHAR(255) DEFAULT NULL, decimal_latitude NUMERIC(10, 7) DEFAULT NULL, decimal_longitude NUMERIC(10, 7) DEFAULT NULL, country_code VARCHAR(10) DEFAULT NULL, event_date VARCHAR(255) DEFAULT NULL,  PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3EABD69195047906 ON cetaf.sid (stable_uri)');
        $this->addSql('CREATE INDEX IDX_3EABD691E45BA08D ON cetaf.sid (herbarium)');
        $this->addSql('COMMENT ON COLUMN cetaf.sid.external_id_from_institution IS \'e.g. GUID in case of Museion, something totally persistent and unique across institution, that will allow a redirect in the feature to the original data provider\'');
        $this->addSql('COMMENT ON COLUMN cetaf.sid.barcode IS \'specimens identificator that allows match the repository photos\'');
        $this->addSql('COMMENT ON COLUMN cetaf.sid.stable_uri IS \'URI assigned via ark.biodiversity.cz\'');
        $this->addSql('COMMENT ON COLUMN cetaf.sid.herbarium IS \'source institution\'');
        $this->addSql('ALTER TABLE cetaf.sid ADD CONSTRAINT FK_3EABD691E45BA08D FOREIGN KEY (herbarium) REFERENCES herbaria (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cetaf.sid DROP CONSTRAINT FK_3EABD691E45BA08D');
        $this->addSql('DROP TABLE cetaf.sid');
    }
}
