<?php

declare(strict_types=1);

namespace Database\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251120092957 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA cetaf');
        $this->addSql('CREATE TABLE cetaf.sid ( id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, lastedit_timestamp TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, herbarium INT NOT NULL, stable_uri VARCHAR(255) NOT NULL, scientific_name_current VARCHAR(255) DEFAULT NULL, family VARCHAR(255) DEFAULT NULL, scientific_name_original VARCHAR(255) DEFAULT NULL, collector_number VARCHAR(255) DEFAULT NULL, collector_name VARCHAR(255) DEFAULT NULL, webscaled_image_link VARCHAR(255) DEFAULT NULL, latitude NUMERIC(10, 7) DEFAULT NULL, longitude NUMERIC(10, 7) DEFAULT NULL, iso_country VARCHAR(10) DEFAULT NULL, collection_date VARCHAR(255) DEFAULT NULL, source_link VARCHAR(255) DEFAULT NULL,PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3EABD69195047906 ON cetaf.sid (stable_uri)');
        $this->addSql('CREATE INDEX IDX_3EABD691E45BA08D ON cetaf.sid (herbarium)');
        $this->addSql('COMMENT ON COLUMN cetaf.sid.herbarium IS \'source institution\'');
        $this->addSql('ALTER TABLE cetaf.sid ADD CONSTRAINT FK_3EABD691E45BA08D FOREIGN KEY (herbarium) REFERENCES herbaria (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cetaf.sid DROP CONSTRAINT FK_3EABD691E45BA08D');
        $this->addSql('DROP TABLE cetaf.sid');
    }
}
