name: Tests

on:
    push:
        branches:
            - test
    workflow_dispatch:  # Manual run
jobs:
    test:
        name: Run tests and collect coverage
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:16
                env:
                    POSTGRES_DB: jacq_test
                    POSTGRES_USER: jacq_test
                    POSTGRES_PASSWORD: jacq_test
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            -   name: Checkout
                uses: actions/checkout@v5
                with:
                    fetch-depth: 0

            #install PHP dependencies
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.4'
                    tools: composer:v2
                    extensions: mbstring, json

            -   name: Get composer cache directory
                id: composer-cache
                working-directory: ./htdocs
                run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            -   name: Cache composer dependencies
                uses: actions/cache@v4.2.4
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-

            -   name: Install Composer dependencies
                working-directory: ./htdocs
                run: composer install --no-progress --prefer-dist --optimize-autoloader

            -   name: Create config file
                working-directory: ./htdocs
                run: cp ./config/local.neon.ci ./config/local.neon

            -   name: Run migrations
                working-directory: ./htdocs
                run: bin/console migrations:migrate --no-interaction

            -   name: Load fixtures
                working-directory: ./htdocs
                run: bin/console doctrine:fixtures:load --no-interaction --purge=truncate

            -   name: Run tests
                working-directory: ./htdocs
                run: vendor/bin/tester -p phpdbg tests/Cases/Unit -s -C

            -   name: Upload results to Codecov
                uses: codecov/codecov-action@v5
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    files: coverage.xml
                    fail_ci_if_error: false
